### ISSUE TITLE
Implementar página de autenticação do supervisor

### ISSUE THREAD

**Issue by victorMagalhaesPacheco** [EscolaDeSaudePublica/sagu-front#1]
# Objetivo

**Eu como** pessoa supervisora da residência multiprofissional
**Quero** me autenticar no sistema do SAGU com CPF e SENHA previamente cadastrados pelos administradores da residência multiprofissional
**Para que** possa ter acesso ao acompanhamento de turmas e residentes

# Contexto

## O que originou

Necessidade da implementação do acompanhamento da residência multiprofissional de forma descentralizada

## Qual solução proposta

Desenvolver uma tela para a autenticação da pessoa supervisora, com os campos CPF e SENHA.

# Fora de Contexto

- Não se aplica

# Critérios de aceitação

- [x] **Dado que** acesso o sistema do SAGU FRONT 
**Quando** preencho os campos obrigatórios CPF e SENHA e clico no botão "Entrar"  
**Então** caso CPF e SENHA corretos, sou redirecionado para a página inicial do sistema

- [x] **Dado que** acesso o sistema do SAGU FRONT 
**Quando** preencho os campos obrigatórios CPF e SENHA e clico no botão "Entrar"  
**Então** caso CPF ou SENHA incorretos, é apresentando uma mensagem informando "CPF ou Senha inválidos"

- [x] **Dado que** acesso o sistema do SAGU FRONT 
**Quando** clico em recuperar senha
**Então** sou redirecionado para uma página de recuperação de senha (necessário refinar)

# Observações

- Épico: https://github.com/EscolaDeSaudePublica/sagu/issues/28
- Atividade vinculada ao backend api: https://github.com/EscolaDeSaudePublica/sagu-api/issues/2

**Comment by matheuscpl** [comment]
@ericsonmoreira Segue o link do protótipo dessa tarefa:
https://www.figma.com/file/QvWTWSkZj05xhD7eECmiIr/Resid%C3%AAncia-Multiprofissional?node-id=0%3A1

**Comment by ericsonmoreira** [comment]
@victorMagalhaesPacheco Já podemos considerar esse card como completo?

**Comment by victorMagalhaesPacheco** [comment]
> @victorMagalhaesPacheco Já podemos considerar esse card como completo?

Sim! Mas não podemos fechar agora, pois precisamos realizar o deskcheck em seguida fazer o deploy pra produção.

**Comment by victorMagalhaesPacheco** [comment]
@victorMagalhaesPacheco Inclusive vamos precisar atualizar o deploy dessa API, devido a mudança recente de servidores, que no caso a API foi tbm, e não foi adicionado nenhum script pra atualizar automaticamente, e se eu não me engano ele está apontando pelo gitlab que está na escola e o ideal é vim do github, pois configurei o continous delivery a API em qualquer push ou PR (falta só configurar os testes pra ficar 100%).
