### ISSUE TITLE
Implementar página para gerenciar a carga horária complementar do residente

### ISSUE THREAD

**Issue by victorMagalhaesPacheco** [EscolaDeSaudePublica/sagu-front#17]
# Objetivo

**Eu como**  pessoa supervisora da residência multiprofissional
**Quero** visualizar uma lista de residentes onde sou responsável e gerenciar todas as carga horária do residentes
**Para que** possa adicionar, atualizar ou remover carga horária do residente para complementar a frequência do mesmo

# Contexto

## O que originou

A implementação da descentralização do acompanhamento por parte do supervisor está também o gerenciamento de carga horária complementar como responsabilidade da pessoa supervisor(a)

## Qual solução proposta

Criar página para listagem de residentes, em seguida gerenciar a carga horária de cada residente onde o supervisor é responsável.

# Fora de Contexto

Não se aplica

# Critérios de aceitação

- [x] **Dado que** sou uma pessoa supervisora da residência multiprofissional
**Quando** acesso a listagem de ofertas onde sou responsável e em seguida clico em gerenciar carga horária complementar
**Então** aparece uma lista com todos os residentes matriculado na instituição onde sou responsável e posso gerenciar qualquer residente sobre a carga horária complementar

- [x] **Dado que** acesso a listagem dos residentes matriculados na oferta
**Quando** acesso o gerenciamento de carga horária complementar do residente
**Então** visualizo a listagem com todas as carga horária já lançada para o residente

- [x] **Dado que**  acesso a listagem dos residentes matriculados na oferta
**Quando** acesso o gerenciamento de carga horária complementar do residente e clico em "adicionar carga horária complementar"
**Então** mostra um formulário com os campos "tipo de carga horária complementar", "tipo de carga horária", "carga horária" e "justificativa" e quando preenchido com os dados corretos, é apresentando uma mensagem de sucesso

# Observações

Implementação backend api: https://github.com/EscolaDeSaudePublica/sagu-api/issues/37

**Comment by ericsonmoreira** [comment]
Figma: https://www.figma.com/file/QvWTWSkZj05xhD7eECmiIr/Resid%C3%AAncia-Multiprofissional?node-id=545%3A0
