### ISSUE TITLE
Implementar template base Material UI

### ISSUE THREAD

**Issue by vicmagpac** [EscolaDeSaudePublica/sagu-front#2]
# Objetivo

**Eu como** desenvolvedor(a) do front sagu
**Quero** utilizar um template base do Material UI
**Para que** possa agilizar o processo de desenvolvimento do front com componentes implementados e testados

# Contexto

## O que originou

Necessidade da implementação de um frontend para acompanhamento da residência multiprofissional de forma descentralizada

## Qual solução proposta

Utilizar um template base do react + material UI. [Demo](https://material-ui.com/store/previews/devias-kit/) e [Github devias material UI](https://github.com/devias-io/material-kit-react)

# Fora de Contexto

- Não se aplica

# Critérios de aceitação

- [x] **Dado que** Inicio a implementação de uma página no front do SAGU
**Quando** necessito de algum componente do material UI
**Então** utilizo os componentes internos do template base com bibliotecas já configuradas

**Comment by ericsonmoreira** [comment]
@victorMagalhaesPacheco, estou confuso. Essa atividade está relacionada com a criação do [front-base](https://github.com/EscolaDeSaudePublica/front-base)?
