### ISSUE TITLE
Correção datas -1 dias no front

### ISSUE THREAD

**Issue by victorMagalhaesPacheco** [EscolaDeSaudePublica/sagu-front#26]
# Objetivo

**Eu como** pessoa supervisora
**Quero** visualizar o período correto das ofertas
**Para que** possa gerenciar as ofertas no período correto

# Critérios de aceitação

- [x] **Dado que** acesso a lista de ofertas
**Quando** visualizo uma oferta com período
**Então** visualizo o período correto

**Comment by ericsonmoreira** [comment]
O JS é bom... só peca com datas.
