### ISSUE TITLE
Implementar página para consulta de turmas vinculadas à pessoa supervisor(a)

### ISSUE THREAD

**Issue by victorMagalhaesPacheco** [EscolaDeSaudePublica/sagu-front#3]
# Objetivo

**Eu como** como pessoa supervisor(a) da residência multiprofissional
**Quero** consultar as turmas na qual estão vinculadas ao meu perfil, baseado nas ofertas de atividades dos módulos ofertados  para a turma
**Para que** eu posso escolher qual turma desejo gerenciar

# Contexto
## O que originou

O desenvolvimento de um módulo de pessoa supervisor(a) no sistema do SAGU consistirá de uma nova interface para a pessoa usuária Supervisora. 
Sendo assim, esta pessoa quando autenticada precisará consultar as suas turmas.

## Qual solução proposta

Criar uma página que irá mostrar uma lista de turmas da pessoa supervisor(a). Adicionar a possibilidade de paginação de 25 em 25, passando o parâmetro page, com o número da página.

# Fora de Contexto

Cadastro, atualização e remoção de turmas.

# Critérios de aceitação

- [x] **Dado que** sou uma pessoa supervisor(a) autenticada  
**Quando** acesso a primeira (home) página do sistema
**Então** visualizo todas as turmas em que estou vinculado para que eu possa gerenciar com os campos código da turma, nome da turma, componente, período

- [x] **Dado que** estou visualizando minhas turmas
**Quando** clico no botão "Gerenciar"
**Então** acesso a lista de todas as ofertas da turma selecionada que sou responsável

# Observações

- EPIC;  https://github.com/EscolaDeSaudePublica/sagu/issues/28
- Atividade vinculada ao backend api: EscolaDeSaudePublica/sagu-api#7

**Comment by matheuscpl** [comment]
Protótipo: https://www.figma.com/file/QvWTWSkZj05xhD7eECmiIr/Resid%C3%AAncia-Multiprofissional?node-id=26%3A0
